languageCode: de-de
title: Klimafreundliche Rezepte

theme: ["PaperMod"]

mainsections: ["posts"]

params:
  defaultTheme: light
  ShowShareButtons: true
  ShareButtons: ["facebook", "twitter", "whatsapp"]
  DateFormat: "_2.01.2006"
  homeInfoParams:
    Title: "Klimafreundliche Rezepte"
    Content: >
      ðŸ‘‹ Willkommen bei der Sammlung klimafreundlicher Rezepte des Klimaschutzprojekts "Klimaschutz einfach machen" aus Bielefeld
      
      - Mitarbeit ist gerne gesehen
      
      - Sources bei [github](https://github.com/Klimaschutz-Einfach-Machen/RezeptDatenbank)

menu:
  main:
    - identifier: search
      name: Suche
      url: /search/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20

outputs:
  home:
    - HTML
    - RSS
    - JSON 
